spring:
  application:
    name: telegram
  kafka:
    consumer:
      auto-offset-reset: earliest
  cloud:
    function:
      definition: coreDataMessage
    stream:
      kafka:
        binder:
          minPartitionCount: 3
      function:
        bindings:
          telegramDataCmd-out-0: telegramDataCmd
      bindings:
        coreDataMessage:
          destination: core.data.message
          group: ${spring.application.name}
        telegramDataCmd:
          destination: telegram.data.command

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
