bot:
  name: budget_planner_bot
  token: 991064577:AAHtI9JsNg8mgR5IRNiveJMLxN9JpZMw4v8

spring:
  application:
    name: "telegram"
  kafka:
    consumer:
      auto-offset-reset: earliest
  cloud:
    stream:
      kafka:
        binder:
          minPartitionCount: 3
          brokers: "localhost:29092"
          producer-properties:
            key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
      bindings:
        coreDataMessage-in-0:
          destination: core.data.message
          group: "${spring.application.name}"
        telegramDataCmd-out-0:
          destination: telegram.data.command
    function:
      definition: "coreDataMessage"
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram
    username: postgres
    password: mysecretpassword

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

server:
  port: 8081