spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/planner
    username: postgres
    password: mysecretpassword
  jpa:
    show-sql: true

bot:
  name: budget_planner_bot
  token: 991064577:AAHtI9JsNg8mgR5IRNiveJMLxN9JpZMw4v8

server:
  port: 8081
