bot:
  name: budget_planner_bot
  token: 991064577:AAHtI9JsNg8mgR5IRNiveJMLxN9JpZMw4v8

spring:
  application:
    name: "telegram"
  kafka:
    consumer:
      auto-offset-reset: earliest
  cloud:
    function:
      definition: coreDataMessage
    stream:
      kafka:
        binder:
          minPartitionCount: 3
          brokers: "localhost:29092"
      function:
        bindings:
          telegramDataCmd-out-0: telegramDataCmd
      bindings:
        coreDataMessage:
          destination: core.data.message
          group: ${spring.application.name}
        telegramDataCmd:
          destination: telegram.data.command
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram
    username: postgres
    password: mysecretpassword

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

server:
  port: 8081
