version: '3.9'

volumes:
  kafka-data:
    driver: local
services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=ROA52xSTRoSCZa8uyJaI_g
    volumes:
      - kafka-data:/var/lib/kafka/data:Z

  kafka-ui:
    image: provectuslabs/kafka-ui
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_NAME=local
    ports:
      - 8090:8080
    links:
      - kafka
    depends_on:
      - kafka

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: planner
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432

  core:
    build:
      context: planner-core
      dockerfile: Dockerfile
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/planner
      - DB_USER=postgres
      - DB_PASS=mysecretpassword
      - BROKER_URL=kafka:9092
    ports:
      - 8080:8080
    depends_on:
      - kafka
      - postgres