UPDATE product p SET p.spended_by='1' WHERE p.spended_by='Кирилл';
UPDATE product p SET p.spended_by='11' WHERE p.spended_by='Maria';

UPDATE product p SET p.category='1' WHERE p.category='RENT' AND p.spended_by='1';
UPDATE product p SET p.category='11' WHERE p.category='PHONES' AND p.spended_by='1';
UPDATE product p SET p.category='21' WHERE p.category='FEED' AND p.spended_by='1';
UPDATE product p SET p.category='141' WHERE p.category='POCKET_MONEY' AND p.spended_by='1';
UPDATE product p SET p.category='31' WHERE p.category='ENTERTAINMENT' AND p.spended_by='1';
UPDATE product p SET p.category='41' WHERE p.category='REALITY' AND p.spended_by='1';
UPDATE product p SET p.category='51' WHERE p.category='GIFTS' AND p.spended_by='1';
UPDATE product p SET p.category='151' WHERE p.category='THERAPY' AND p.spended_by='1';
UPDATE product p SET p.category='61' WHERE p.category='HEALTH' AND p.spended_by='1';
UPDATE product p SET p.category='71' WHERE p.category='TRANSPORT' AND p.spended_by='1';
UPDATE product p SET p.category='271' WHERE p.category='WOMAN_STUFF' AND p.spended_by='1';
UPDATE product p SET p.category='131' WHERE p.category='REDUNDANT' AND p.spended_by='1';
UPDATE product p SET p.category='81' WHERE p.category='TRAVEL' AND p.spended_by='1';
UPDATE product p SET p.category='111' WHERE p.category='LUNCH' AND p.spended_by='1';
UPDATE product p SET p.category='91' WHERE p.category='OTHER' AND p.spended_by='1';
UPDATE product p SET p.category='101' WHERE p.category='CLOTHES' AND p.spended_by='1';
UPDATE product p SET p.category='121' WHERE p.category='EDUCATION' AND p.spended_by='1';

UPDATE product p SET p.category='161' WHERE p.category='RENT' AND p.spended_by='11';
UPDATE product p SET p.category='171' WHERE p.category='PHONES' AND p.spended_by='11';
UPDATE product p SET p.category='181' WHERE p.category='FEED' AND p.spended_by='11';
UPDATE product p SET p.category='321' WHERE p.category='POCKET_MONEY' AND p.spended_by='11';
UPDATE product p SET p.category='191' WHERE p.category='ENTERTAINMENT' AND p.spended_by='11';
UPDATE product p SET p.category='201' WHERE p.category='REALITY' AND p.spended_by='11';
UPDATE product p SET p.category='211' WHERE p.category='GIFTS' AND p.spended_by='11';
UPDATE product p SET p.category='331' WHERE p.category='THERAPY' AND p.spended_by='11';
UPDATE product p SET p.category='221' WHERE p.category='HEALTH' AND p.spended_by='11';
UPDATE product p SET p.category='231' WHERE p.category='TRANSPORT' AND p.spended_by='11';
UPDATE product p SET p.category='301' WHERE p.category='WOMAN_STUFF' AND p.spended_by='11';
UPDATE product p SET p.category='311' WHERE p.category='REDUNDANT' AND p.spended_by='11';
UPDATE product p SET p.category='241' WHERE p.category='TRAVEL' AND p.spended_by='11';
UPDATE product p SET p.category='281' WHERE p.category='LUNCH' AND p.spended_by='11';
UPDATE product p SET p.category='251' WHERE p.category='OTHER' AND p.spended_by='11';
UPDATE product p SET p.category='261' WHERE p.category='CLOTHES' AND p.spended_by='11';
UPDATE product p SET p.category='291' WHERE p.category='EDUCATION' AND p.spended_by='11';
