spring:
  cloud:
    stream:
      kafka:
        binder:
          minPartitionCount: 3
          brokers: kafka:9092
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:postgresql://localhost:5432/planner
    username: postgres
    password: mysecretpassword
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
